F 01
ignatiqq/carsharing-app pull request #2
Opened 2022-03-20 22:32 UTC by ignatiqq

logic for slider

2022-03-21 13:31 UTC, EvgeniyaFilatova requested changes

2022-03-21 13:31 UTC, EvgeniyaFilatova commented on src/api/makeRequest.ts
> +    return fetch(url, {
- [ ] Попробуй использовать axios для запросов

2022-03-21 13:31 UTC, EvgeniyaFilatova commented on src/components/Sidebar/Sidebar.tsx
> +import { setSidebarOpen } from 'store/commonSettings/actions';
- [x]  В чем необходимость хранить данное состояние в сторе? Хватит и внутреннего стейта

2022-03-21 13:31 UTC, EvgeniyaFilatova commented on src/components/Sidebar/Sidebar.tsx
> +  })
- [x] Думаю, что в useEffect можно передать вторым аргументом пустой массив, чтобы не было повторных запусков

2022-03-21 13:31 UTC, EvgeniyaFilatova commented on src/components/Sidebar/Sidebar.tsx
> +  useEffect(() => {
- [ ] Это для обработки клика на кнопку меню? Так делать некорректно. Можно же по событию click на кнопку менять состояние меню. addEventListener вообще использовать следует только в крайней случае в реакте

2022-03-21 13:31 UTC, EvgeniyaFilatova commented on src/pages/MainPage/SliderSide/sliderCustomStyles.scss
> +// .swiper-button-prev {
- [x] Не забывай удалять код, который уже не нужен. Можно настроить eslint и stylelint для удобства

2022-03-21 13:39 UTC, ignatiqq commented on src/api/makeRequest.ts
> +    return fetch(url, {
> * [ ]  Попробуй использовать axios для запросов

Я хотел создать абстракцию, которая бы не зависела от используемого для запроса инструмента, чтобы можно было легко мигрировать, как с axios на fetch, так и нааборот

2022-03-21 13:40 UTC, ignatiqq commented on src/components/Sidebar/Sidebar.tsx
> +  useEffect(() => {
> * [ ]  Это для обработки клика на кнопку меню? Так делать некорректно. Можно же по событию click на кнопку менять состояние меню. addEventListener вообще использовать следует только в крайней случае в реакте

Это обработка нажатия Escape, для того чтобы по клику на нее можно было закрыть меню соответственно

2022-03-21 13:51 UTC, EvgeniyaFilatova commented on src/components/Sidebar/Sidebar.tsx
> +  useEffect(() => {
Для escape у тебя выше. А это у тебя обработчик для события мыши (в аргументах функции e: MouseEvent)

2022-03-21 13:52 UTC, EvgeniyaFilatova commented on src/api/makeRequest.ts
> +    return fetch(url, {
А axios использовал уже?

2022-03-21 14:41 UTC, ignatiqq commented on src/components/Sidebar/Sidebar.tsx
> +  useEffect(() => {
> Для escape у тебя выше. А это у тебя обработчик для события мыши (в аргументах функции e: MouseEvent)

Я не знаю, как по другому на любой клик по ссылке в сайдбаре закрывать его, есть идеи?

2022-03-21 14:41 UTC, ignatiqq commented on src/api/makeRequest.ts
> +    return fetch(url, {
> А axios использовал уже когда-либо?

Да, использовал, на нескольких проектах

2022-03-23 13:19 UTC, EvgeniyaFilatova commented on src/components/Sidebar/Sidebar.tsx
> +  useEffect(() => {
Да, добавить пропс onClick в компонент MenuBtn (там же ссылки?), в который будешь передавать такую функцию:
`() => setSidebarOpen(false)`

2022-03-23 13:20 UTC, EvgeniyaFilatova commented on src/components/Sidebar/Sidebar.tsx
> +     {sidebarOpen && <div className={styles.overlay}></div>}
- [ ] Здесь можно самозакрывающийся тег использовать, children же нет

2022-03-23 13:21 UTC, EvgeniyaFilatova commented on src/components/SidebarNavigation/SidebarNav.tsx
> +              <InstagramIcon style={{margin: "0px 24px"}} className={styles.socialsLink} />
- [ ] А почему здесь инлайн-стиль сделал?

2022-03-23 13:22 UTC, EvgeniyaFilatova commented on src/pages/MainPage/InfoSide/InfoSide.tsx
> +        {/* <Button onClick={toggleSidebarHandler} className={styles.buttonHeader}>
- [x] Можно совсем удалить?

2022-03-23 13:24 UTC, EvgeniyaFilatova commented
- [ ] На мобильном разрешении в меню должна быть кнопка смены языка
![image](https://user-images.githubusercontent.com/90593835/159709697-6e6e8f1f-f80c-4040-87fc-f2ffeb732bd7.png)

2022-03-23 13:33 UTC, ignatiqq commented on src/components/Sidebar/Sidebar.tsx
> +  useEffect(() => {
> Да, добавить пропс onClick в компонент MenuBtn (там же ссылки?), в который будешь передавать такую функцию: `() => setSidebarOpen(false)`

Видимо мы друг друга не очень понимаем, это логика закрытия сайдбара не по клику на кнопку закрытия(бургер), а на сами ссылки в nav, у нас же spa и приложение не обновляется и при переходе на другой роут(страницу) я хочу закрывать сайдбар.

2022-04-14 09:15 UTC, merged